# The Boston Housing Dataset

In [31]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [32]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [33]:
boston = load_boston()
boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [34]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size, 1)

x_data[:3]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00]])

In [35]:
from sklearn import preprocessing

# 0-1 사이의 값으로 바꿈
minmax_scale = preprocessing.MinMaxScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, 0.00000000e+00,
        3.14814815e-01, 5.77505269e-01, 6.41606591e-01, 2.69203139e-01,
        0.00000000e+00, 2.08015267e-01, 2.87234043e-01, 1.00000000e+00,
        8.96799117e-02],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, 0.00000000e+00,
        1.72839506e-01, 5.47997701e-01, 7.82698249e-01, 3.48961980e-01,
        4.34782609e-02, 1.04961832e-01, 5.53191489e-01, 1.00000000e+00,
        2.04470199e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, 0.00000000e+00,
        1.72839506e-01, 6.94385898e-01, 5.99382080e-01, 3.48961980e-01,
        4.34782609e-02, 1.04961832e-01, 5.53191489e-01, 9.89737254e-01,
        6.34657837e-02]])

In [36]:
from sklearn.model_selection import train_test_split

# 샘플링 먼저 해주기
X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size=0.2)

In [37]:
from sklearn import linear_model

regr = linear_model.LinearRegression(fit_intercept=True, #상수항
                                    normalize=False, #std
                                    copy_X=True, #복사
                                    n_jobs=8) #cpu 개수

# 모델이 생성됨
regr.fit(X_train, y_train)
regr

LinearRegression(n_jobs=8)

In [38]:
# coef와 절편
regr.coef_, regr.intercept_

(array([[ -8.36048307,   4.76786263,   0.36016248,   2.32666231,
          -8.66211359,  18.26810101,   0.4454353 , -16.56532887,
           7.73743299,  -7.91378228,  -7.93394721,   4.03035765,
         -21.48574951]]),
 array([27.32540667]))

y^ = w0 + w1x1 + w2x2 + ... + w13x13

- w0 = regr.intercept_
- wi = regr.coef_

In [39]:
regr.predict(x_data[:5])

array([[-772.81279107],
       [-541.87192938],
       [-442.45505708],
       [-282.98878945],
       [-319.03387782]])

In [41]:
y_true = y_test
y_pred = regr.predict(X_test)

In [45]:
np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

4.890845982113926

In [48]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_true, y_pred))

4.890845982113926