## array의 생성

In [2]:
import numpy as np

test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [5]:
type(test_array[3])

numpy.float64

In [6]:
test_array.dtype

dtype('float64')

In [7]:
test_array.shape

(4,)

## reshape

In [8]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [9]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [10]:
np.array(test_matrix).reshape(-1, 2).shape

# -1 : size를 기반으로 row 개수 선정

(4, 2)

In [13]:
test = np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [15]:
test.reshape(-1, 1)

# 2차원

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

## flatt or flatten()
- 다차원 array를 1차원 array로 변환

In [16]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

## arange

In [19]:
np.arange(30).reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [20]:
np.arange(0, 5, 0.5)

# (시작, 끝, step)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## something_like
- 기존 ndarray의 shape 크기만큼 1, 0 또는 empty array를 반환

In [25]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## eye
- 대각선이 1인 행렬, k값의 시작 index의 변경이 가능

In [26]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3, 5, k=2)
# k : start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## diag
- 대각 행렬의 값을 추출함

In [32]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

In [34]:
np.diag(matrix, k=1)

array([1, 5])

## sum

In [37]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
test_array.sum(dtype=np.float)

55.0

In [42]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
test_array.sum(axis=1)

array([10, 26, 42])

In [45]:
test_array.sum(axis=0)

# 새로 생기는 축이 axis=0이 된다.

array([15, 18, 21, 24])

## broadcasting
- shape이 다른 배열 간 연산을 지원하는 기능

In [46]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

In [47]:
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

- scalar-vector 외에도 vector-matrix 간의 연산도 지원

## all & any

In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [58]:
np.any(a>5), np.any(a<0)

(True, False)

In [57]:
np.all(a>5), np.all(a<10)

(False, True)

In [60]:
a = np.arange(3)
a

array([0, 1, 2])

In [61]:
np.where(a>0, 3, 2)

# where (condition, True, False)

array([2, 3, 3])

In [62]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [64]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [67]:
np.isfinite(a)

array([ True, False, False])

## argumax & argmin

In [68]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

In [69]:
a = np.array([[1, 2, 4, 7], [9, 888, 6, 45], [9, 76, 3, 4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

# axis=1 : row 기준으로 (7, 888, 76)
# axis=0 : col 기준으로 (1, 2, 3, 4)

(array([3, 1, 1]), array([0, 0, 2, 2]))

## fancy index
- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [70]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 int로 선언
a[b]

array([2., 2., 4., 8., 6., 4.])

In [71]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])